version: '3'
services: 
    db: 
        image: postgres
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
    web:
        build: .
        volumes: 
            - .:/usr/src/app
        ports:
            - "8000:8000"